// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisAcademyApp.Data;

#nullable disable

namespace TennisAcademyApp.Data.Migrations
{
    [DbContext(typeof(TennisAcademyDbContext))]
    [Migration("20250812173329_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Bag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Bag Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Bag Brand");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Bag Image");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Bag Model");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Bag Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Bags", t =>
                        {
                            t.HasComment("Bags Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            ImageUrl = "https://cdn.media.amplience.net/i/sportinglife/25918789_0/Team-3-Pack-Tennis-Bag?$default$&fmt=auto&w=540&h=540",
                            Model = "Team 3-Pack",
                            Price = 59.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Head",
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/20/c1/2b/1721072068/head-tour-team-6r-combi-black-mixed-1.jpg?ts=1745860751",
                            Model = "Tour Team 6R",
                            Price = 89.99m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Babolat",
                            ImageUrl = "https://m.media-amazon.com/images/I/61vGrieRbCL._UF1000,1000_QL80_.jpg",
                            Model = "Pure Drive RHx6",
                            Price = 99.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Yonex",
                            ImageUrl = "https://www.midwestracquetsports.com/images/xl/BAG92429BK.jpg?v=1",
                            Model = "Pro Series 9-Pack",
                            Price = 129.99m,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BagCart", b =>
                {
                    b.Property<int>("BagId")
                        .HasColumnType("int")
                        .HasComment("Foreign Key of Bag");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of Bags in Cart");

                    b.HasKey("BagId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BagCart");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Ball", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Ball Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Ball Brand");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Racket Image");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Ball Model");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Ball Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Balls", t =>
                        {
                            t.HasComment("Balls Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            ImageUrl = "https://m.media-amazon.com/images/I/715MEN61aPL._UF1000,1000_QL80_.jpg",
                            Model = "US Open Extra Duty",
                            Price = 12.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Head",
                            ImageUrl = "https://cdn.sportdepot.bg/files/catalog/detail/570823_01.jpg",
                            Model = "Tour XT",
                            Price = 11.49m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dunlop",
                            ImageUrl = "https://m.media-amazon.com/images/I/618MvroxyXL._UF1000,1000_QL80_.jpg",
                            Model = "ATP Championship",
                            Price = 10.99m,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BallCart", b =>
                {
                    b.Property<int>("BallId")
                        .HasColumnType("int")
                        .HasComment("Foreign Key of Ball");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of Balls in Cart");

                    b.HasKey("BallId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BallCart", t =>
                        {
                            t.HasComment("Ball Cart");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Coach Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Coach Age");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Coach Description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Coach Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Coach Name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Coach Nationality");

                    b.HasKey("CoachId");

                    b.ToTable("Coaches", t =>
                        {
                            t.HasComment("Tennis Academy Coaches");
                        });

                    b.HasData(
                        new
                        {
                            CoachId = 1,
                            Age = 38,
                            Description = "One of the greatest tennis players of all time, known for his clay court dominance.",
                            ImageUrl = "~/pictures/rafa.jpg",
                            Name = "Rafael Nadal",
                            Nationality = "Spanish"
                        },
                        new
                        {
                            CoachId = 2,
                            Age = 43,
                            Description = "Swiss tennis legend with unmatched elegance and 20 Grand Slam titles.",
                            ImageUrl = "https://a.espncdn.com/combiner/i?img=/i/headshots/tennis/players/full/425.png",
                            Name = "Roger Federer",
                            Nationality = "Swiss"
                        },
                        new
                        {
                            CoachId = 3,
                            Age = 37,
                            Description = "Serbian champion, known for his resilience and complete game.",
                            ImageUrl = "https://a.espncdn.com/i/headshots/tennis/players/full/296.png",
                            Name = "Novak Djokovic",
                            Nationality = "Serbian"
                        },
                        new
                        {
                            CoachId = 4,
                            Age = 55,
                            Description = "American icon who redefined tennis in the 90s with a colorful personality.",
                            ImageUrl = "https://www.atptour.com/-/media/alias/player-headshot/A092",
                            Name = "Andre Agassi",
                            Nationality = "American"
                        },
                        new
                        {
                            CoachId = 5,
                            Age = 68,
                            Description = "Swedish legend with ice-cold nerves and six French Open titles.",
                            ImageUrl = "https://lavercup.com/wp-content/uploads/2022/12/figure-borg-2.png",
                            Name = "Björn Borg",
                            Nationality = "Swedish"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Racket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Racket Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Racket Brand");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Racket Image");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Racket Model");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Racket Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Available in stock");

                    b.HasKey("Id");

                    b.ToTable("Rackets", t =>
                        {
                            t.HasComment("Rackets Shop");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Wilson",
                            ImageUrl = "https://cdncloudcart.com/28710/products/images/134337/tenis-raketa-wilson-pro-staff-rf-97-v13-0-tns-fr-image_6358bfebb40a9_800x800.jpeg?1666760684",
                            Model = "Pro Staff 97",
                            Price = 349.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Babolat",
                            ImageUrl = "https://babolat.bg/image/cache/catalog/tennis/2024/rackets/101474/101474-Pure_Drive_98-136-1-Face_2-250x250.jpg",
                            Model = "Pure Drive",
                            Price = 299.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Head",
                            ImageUrl = "https://i.sportisimo.com/products/images/1104/1104555/700x700/head-graphene-360-speed-mp_1.jpg",
                            Model = "Graphene 360+ Speed",
                            Price = 279.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Yonex",
                            ImageUrl = "https://us.yonex.com/cdn/shop/files/EZ0898_BlastBlue_5868.jpg?v=1739481973&width=1946",
                            Model = "Ezone 98",
                            Price = 319.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Prince",
                            ImageUrl = "https://images.squarespace-cdn.com/content/v1/56e9b38c2b8dde820241b62d/1471886555425-JT9KKFKPOL4FNLAV9ZB0/r2.jpg",
                            Model = "Tour 100P",
                            Price = 259.99m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Tecnifibre",
                            ImageUrl = "https://www.tecnifibre.com/dw/image/v2/BHDN_PRD/on/demandware.static/-/Sites-tecnifibre-master-catalog/default/dwcf93310b/hi-res/T-FIGHT%202025/Packshots/305S/14FI305S5_04.jpg?sw=608&sh=608&sm=fit",
                            Model = "TFight 305",
                            Price = 289.99m,
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.RacketCart", b =>
                {
                    b.Property<int>("RacketId")
                        .HasColumnType("int")
                        .HasComment("Foreign Key of Racket");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign Key of IdentityUser");

                    b.Property<int?>("BallId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of Rackets in Cart");

                    b.HasKey("RacketId", "UserId");

                    b.HasIndex("BallId");

                    b.HasIndex("UserId");

                    b.ToTable("RacketCart", t =>
                        {
                            t.HasComment("Racket Cart");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Reservation Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int")
                        .HasComment("Choosing a coach");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date Select");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the session");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Player Notes");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Player Identifer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("int")
                        .HasComment("Choosing a surface");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int")
                        .HasComment("Choosing a training type");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SurfaceId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasComment("Player Reservations");
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Surface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Surface Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Ïmage of the surface");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Surface Name");

                    b.HasKey("Id");

                    b.ToTable("Surfaces", t =>
                        {
                            t.HasComment("Tennis Academy Surfaces");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.edwardssports.co.uk/pub/media/magefan_blog/Clay_Tennis_Courts.jpg",
                            Name = "Clay"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.tennisnerd.net/wp-content/uploads/2024/06/grass-tennis.webp",
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://asltenniscourts.com.au/wp-content/uploads/2021/03/AdobeStock_253105355-1024x683.jpeg",
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Training Type Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Training Type Name");

                    b.HasKey("Id");

                    b.ToTable("Trainings", t =>
                        {
                            t.HasComment("Tennis Academy Trainings");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physical Conditioning Routine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technical Skill Development"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tactical Game Strategy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mental Toughness Training"
                        });
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.UserFavourite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign Key which references to IdentityUser");

                    b.Property<int>("CoachId")
                        .HasColumnType("int")
                        .HasComment("Foreign Key which references to Coach");

                    b.HasKey("UserId", "CoachId");

                    b.HasIndex("CoachId");

                    b.ToTable("UserFavourites", t =>
                        {
                            t.HasComment("Users Favourite Coach");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BagCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Bag", "Bag")
                        .WithMany("BagCarts")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.BallCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Ball", "Ball")
                        .WithMany()
                        .HasForeignKey("BallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ball");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.RacketCart", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Ball", null)
                        .WithMany("RacketCarts")
                        .HasForeignKey("BallId");

                    b.HasOne("TennisAcademyApp.Data.Models.Racket", "Racket")
                        .WithMany("RacketCart")
                        .HasForeignKey("RacketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Racket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Reservation", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Coach", "Coach")
                        .WithMany("Reservations")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.Surface", "Surface")
                        .WithMany("Reservations")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisAcademyApp.Data.Models.TrainingType", "TrainingType")
                        .WithMany("Reservations")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Player");

                    b.Navigation("Surface");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.UserFavourite", b =>
                {
                    b.HasOne("TennisAcademyApp.Data.Models.Coach", "Coach")
                        .WithMany("UsersCoaches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Bag", b =>
                {
                    b.Navigation("BagCarts");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Ball", b =>
                {
                    b.Navigation("RacketCarts");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Coach", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("UsersCoaches");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Racket", b =>
                {
                    b.Navigation("RacketCart");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.Surface", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TennisAcademyApp.Data.Models.TrainingType", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
