<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GTranslate" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TennisAcademy.Data.Models\TennisAcademyApp.Data.Models.csproj" />
    <ProjectReference Include="..\TennisAcademy.Data\TennisAcademyApp.Data.csproj" />
    <ProjectReference Include="..\TennisAcademyApp.ViewModels\TennisAcademyApp.ViewModels.csproj" />
  </ItemGroup>

</Project>
